# Generated by Django 4.0.5 on 2022-06-21 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'genders',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=45)),
                ('price', models.IntegerField()),
                ('is_adult', models.BooleanField(default=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_products', to='products.category')),
                ('collections', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_products', to='products.collection')),
                ('genders', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_products', to='products.gender')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Product_Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_products_colors', to='products.color')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_products_colors', to='products.product')),
            ],
            options={
                'db_table': 'products_colors',
            },
        ),
        migrations.CreateModel(
            name='Product_Color_Image_Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('products_colors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_products_colors_image_urls', to='products.product_color')),
            ],
            options={
                'db_table': 'products_colors_image_urls',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
        migrations.CreateModel(
            name='Product_Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('products_colors_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_color_image_url_product_options', to='products.product_color_image_url')),
                ('sizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_product_options', to='products.size')),
            ],
            options={
                'db_table': 'product_options',
            },
        ),
    ]
