# Generated by Django 4.0.5 on 2022-06-24 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_carts'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolorimage',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_products_colors_images', to='products.color'),
        ),
        migrations.AlterField(
            model_name='productcolorimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_products_colors_images', to='products.product'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('product_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_option_carts', to='products.productoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_carts', to='users.user')),
            ],
            options={
                'db_table': 'carts',
            },
        ),
    ]
