# Generated by Django 4.0.5 on 2022-06-27 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_cart_count_alter_productoption_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='size',
            new_name='sizes',
        ),
    ]
